services:
  mariadb:
    image: mariadb:11.8.2
    environment:
      MYSQL_USER: taskbook
      MYSQL_PASSWORD: taskbook
      MYSQL_DATABASE: taskbook
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_bin --max-allowed-packet=67108864

  phpmyadmin:
    image: phpmyadmin:5.2.2
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "127.0.0.1:3307:80"
