name: Build & Push Docker Images

on:
  push:
    tags: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ taskbook-backend, taskbook-frontend ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')  # Only login when we intend to push (i.e. tag builds)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          build-args: |
            APP_VERSION=${{ github.ref_name }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }} # true on tag, false on branch
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
