name: Weekly Node.js CI

on:
  # Every Sunday at midnight UTC
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: taskbook-frontend

    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "taskbook-frontend/package-lock.json"

      - run: npm ci

      - run: npm run prettier -- --check

      - run: npm run build --if-present
