name: Node.js CI

on:
  push:
    branches: ['main']
    paths:
      - 'taskbook-fe/**'
  pull_request:
    branches: ['main']
    paths:
      - 'taskbook-fe/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: taskbook-fe

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'taskbook-fe/package-lock.json'

      - run: npm ci

      - run: npm run build --if-present
